version: '3'
services:
  automation_hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - automation_grid_network
  automation_chrome:
    image: selenium/node-chrome
    networks:
      - automation_grid_network
    environment:
      - HUB_HOST=automation_hub
  automation_firefox:
    image: selenium/node-firefox
    networks:
      - automation_grid_network
    environment:
      - HUB_HOST=automation_hub
  automation_maven_build:
    image: maven:3.5.3-jdk-8
    networks:
      - automation_grid_network
    environment:
          - MAVEN_CONFIG=/var/maven/.m2
    volumes:
      - ${HOME}/.m2:/var/maven/.m2
      - ${WORKSPACE}:/usr/src/mymaven
    working_dir:
      '/usr/src/mymaven'
    command :
      mvn -B -s pipeline/devops-settings.xml clean test -Duser.home=/var/maven
    user: ${CURRENT_UID}
networks:
  automation_grid_network:
  
  